$(document).ready(function(){
    $('#fa-1').click(function(){
        $('#fa-1').toggleClass('active')
    })
     $('#fa-1').click(function(){
        $('#bar-description-1').toggleClass('active')
    })
    $('#fa-2').click(function(){
        $('#fa-2').toggleClass('active')
    })
     $('#fa-2').click(function(){
        $('#bar-description-2').toggleClass('active')
    })
    $('#fa-3').click(function(){
        $('#fa-3').toggleClass('active')
    })
     $('#fa-3').click(function(){
        $('#bar-description-3').toggleClass('active')
    })
    $('#fa-4').click(function(){
        $('#fa-4').toggleClass('active')
    })
     $('#fa-4').click(function(){
        $('#bar-description-4').toggleClass('active')
    })
    $('#fa-5').click(function(){
        $('#fa-5').toggleClass('active')
    })
     $('#fa-5').click(function(){
        $('#bar-description-5').toggleClass('active')
    })
    $('#fa-6').click(function(){
        $('#fa-6').toggleClass('active')
    })
     $('#fa-6').click(function(){
        $('#bar-description-6').toggleClass('active')
    })
    $('#fa-7').click(function(){
        $('#fa-7').toggleClass('active')
    })
     $('#fa-7').click(function(){
        $('#bar-description-7').toggleClass('active')
    })
    $('#fa-8').click(function(){
        $('#fa-8').toggleClass('active')
    })
     $('#fa-8').click(function(){
        $('#bar-description-8').toggleClass('active')
    })
    $('#fa-9').click(function(){
        $('#fa-9').toggleClass('active')
    })
     $('#fa-9').click(function(){
        $('#bar-description-9').toggleClass('active')
    })
    $('#fa-10').click(function(){
        $('#fa-10').toggleClass('active')
    })
     $('#fa-10').click(function(){
        $('#bar-description-10').toggleClass('active')
    })
    $('#fa-11').click(function(){
        $('#fa-11').toggleClass('active')
    })
     $('#fa-11').click(function(){
        $('#bar-description-11').toggleClass('active')
    })
    $('#tous-les-hotels').click(function(){
        $('.tous').fadeIn(1000);
    })
    $('#populaire').click(function(){
         $('.tous').fadeOut(1000);
        $('.populaire').fadeIn(1000);
    });
    $('#prix-bas').click(function(){
        $('.tous').fadeOut(1000);
        $('.prix-bas').fadeIn(1000);
    })
     $('#top-standing').click(function(){
        $('.tous').fadeOut(1000);
        $('.top').fadeIn(1000);
    });
     $('#trois').click(function(){
        $('.tous').fadeOut(1000);
        $('.trois').fadeIn(1000);
    });
     $('#quatre').click(function(){
        $('.tous').fadeOut(1000);
        $('.quatre').fadeIn(1000);
    });
     $('#cinq').click(function(){
        $('.tous').fadeOut(1000);
        $('.cinq').fadeIn(1000);
    })
})